version: '3'

services:
  app:
    container_name: webhook-app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - TIMEOUT=300000 # 5 minutos
    ports:
     - 3000:3000